### ISSUE TITLE
unexpected behavior in code

### ISSUE THREAD

**Issue by stephantul** [Loicdelanghe/CAI#2]
I expected the value of `x` in your function to be the "limit" in the exercise, in this case 4000000. After perusing your code, I see that your `x` here is the `n`th number in the fibonacci sequence. 

While your code gives the correct result, it is unhandy that the user first has to figure out which number in the fibonacci sequence is the desired number for the problem. e.g. if I were to give you the same problem, but with a different "limit" value, you'd first have to figure out which value of `x` is the correct one for this problem. 

If you want, you can try to add the limit directly into the function as a parameter.

**Comment by Loicdelanghe** [comment]
Thank you for the feedback. I admit the code wasn't very user friendly but I've modified it now so it should accept user input. 
I have also taken care of the stylistic problems (indentation and script name).

**Comment by stephantul** [comment]
Ok, I tested it, and it looks good!
